export const COUNTRIES = [
  { code: "US", name: "United States", flag: "🇺🇸" },
  { code: "GB", name: "United Kingdom", flag: "🇬🇧" },
  { code: "CA", name: "Canada", flag: "🇨🇦" },
  { code: "AU", name: "Australia", flag: "🇦🇺" },
  { code: "DE", name: "Germany", flag: "🇩🇪" },
  { code: "FR", name: "France", flag: "🇫🇷" },
  { code: "IT", name: "Italy", flag: "🇮🇹" },
  { code: "ES", name: "Spain", flag: "🇪🇸" },
  { code: "NL", name: "Netherlands", flag: "🇳🇱" },
  { code: "BE", name: "Belgium", flag: "🇧🇪" },
  { code: "CH", name: "Switzerland", flag: "🇨🇭" },
  { code: "AT", name: "Austria", flag: "🇦🇹" },
  { code: "SE", name: "Sweden", flag: "🇸🇪" },
  { code: "NO", name: "Norway", flag: "🇳🇴" },
  { code: "DK", name: "Denmark", flag: "🇩🇰" },
  { code: "FI", name: "Finland", flag: "🇫🇮" },
  { code: "PL", name: "Poland", flag: "🇵🇱" },
  { code: "CZ", name: "Czech Republic", flag: "🇨🇿" },
  { code: "PT", name: "Portugal", flag: "🇵🇹" },
  { code: "GR", name: "Greece", flag: "🇬🇷" },
  { code: "IE", name: "Ireland", flag: "🇮🇪" },
  { code: "JP", name: "Japan", flag: "🇯🇵" },
  { code: "CN", name: "China", flag: "🇨🇳" },
  { code: "IN", name: "India", flag: "🇮🇳" },
  { code: "SG", name: "Singapore", flag: "🇸🇬" },
  { code: "MY", name: "Malaysia", flag: "🇲🇾" },
  { code: "TH", name: "Thailand", flag: "🇹🇭" },
  { code: "PH", name: "Philippines", flag: "🇵🇭" },
  { code: "ID", name: "Indonesia", flag: "🇮🇩" },
  { code: "VN", name: "Vietnam", flag: "🇻🇳" },
  { code: "KR", name: "South Korea", flag: "🇰🇷" },
  { code: "NG", name: "Nigeria", flag: "🇳🇬" },
  { code: "ZA", name: "South Africa", flag: "🇿🇦" },
  { code: "EG", name: "Egypt", flag: "🇪🇬" },
  { code: "KE", name: "Kenya", flag: "🇰🇪" },
  { code: "GH", name: "Ghana", flag: "🇬🇭" },
  { code: "BR", name: "Brazil", flag: "🇧🇷" },
  { code: "MX", name: "Mexico", flag: "🇲🇽" },
  { code: "AR", name: "Argentina", flag: "🇦🇷" },
  { code: "CL", name: "Chile", flag: "🇨🇱" },
  { code: "CO", name: "Colombia", flag: "🇨🇴" },
  { code: "PE", name: "Peru", flag: "🇵🇪" },
  { code: "ZW", name: "Zimbabwe", flag: "🇿🇼" },
  { code: "RU", name: "Russia", flag: "🇷🇺" },
  { code: "UA", name: "Ukraine", flag: "🇺🇦" },
  { code: "TR", name: "Turkey", flag: "🇹🇷" },
  { code: "SA", name: "Saudi Arabia", flag: "🇸🇦" },
  { code: "AE", name: "United Arab Emirates", flag: "🇦🇪" },
  { code: "IL", name: "Israel", flag: "🇮🇱" },
  { code: "PK", name: "Pakistan", flag: "🇵🇰" },
  { code: "BD", name: "Bangladesh", flag: "🇧🇩" },
  { code: "LK", name: "Sri Lanka", flag: "🇱🇰" },
  { code: "HK", name: "Hong Kong", flag: "🇭🇰" },
  { code: "TW", name: "Taiwan", flag: "🇹🇼" },
  { code: "NZ", name: "New Zealand", flag: "🇳🇿" },
  { code: "FJ", name: "Fiji", flag: "🇫🇯" },
  { code: "TZ", name: "Tanzania", flag: "🇹🇿" },
  { code: "UG", name: "Uganda", flag: "🇺🇬" },
  { code: "RW", name: "Rwanda", flag: "🇷🇼" },
  { code: "ET", name: "Ethiopia", flag: "🇪🇹" },
  { code: "SN", name: "Senegal", flag: "🇸🇳" },
  { code: "CI", name: "Côte d'Ivoire", flag: "🇨🇮" },
  { code: "CM", name: "Cameroon", flag: "🇨🇲" },
  { code: "MA", name: "Morocco", flag: "🇲🇦" },
  { code: "DZ", name: "Algeria", flag: "🇩🇿" },
  { code: "TN", name: "Tunisia", flag: "🇹🇳" },
  { code: "LB", name: "Lebanon", flag: "🇱🇧" },
  { code: "JO", name: "Jordan", flag: "🇯🇴" },
  { code: "PS", name: "Palestine", flag: "🇵🇸" },
  { code: "IQ", name: "Iraq", flag: "🇮🇶" },
  { code: "IR", name: "Iran", flag: "🇮🇷" },
  { code: "KW", name: "Kuwait", flag: "🇰🇼" },
  { code: "QA", name: "Qatar", flag: "🇶🇦" },
  { code: "OM", name: "Oman", flag: "🇴🇲" },
  { code: "BH", name: "Bahrain", flag: "🇧🇭" },
  { code: "VE", name: "Venezuela", flag: "🇻🇪" },
  { code: "EC", name: "Ecuador", flag: "🇪🇨" },
  { code: "BO", name: "Bolivia", flag: "🇧🇴" },
  { code: "PY", name: "Paraguay", flag: "🇵🇾" },
  { code: "UY", name: "Uruguay", flag: "🇺🇾" },
  { code: "CR", name: "Costa Rica", flag: "🇨🇷" },
  { code: "PA", name: "Panama", flag: "🇵🇦" },
  { code: "GT", name: "Guatemala", flag: "🇬🇹" },
  { code: "HN", name: "Honduras", flag: "🇭🇳" },
  { code: "SV", name: "El Salvador", flag: "🇸🇻" },
  { code: "NI", name: "Nicaragua", flag: "🇳🇮" },
  { code: "DO", name: "Dominican Republic", flag: "🇩🇴" },
  { code: "CU", name: "Cuba", flag: "🇨🇺" },
  { code: "JM", name: "Jamaica", flag: "🇯🇲" },
  { code: "TT", name: "Trinidad and Tobago", flag: "🇹🇹" },
  { code: "BB", name: "Barbados", flag: "🇧🇧" },
  { code: "BS", name: "Bahamas", flag: "🇧🇸" },
  { code: "GY", name: "Guyana", flag: "🇬🇾" },
  { code: "SR", name: "Suriname", flag: "🇸🇷" },
  { code: "BZ", name: "Belize", flag: "🇧🇿" },
  { code: "MM", name: "Myanmar", flag: "🇲🇲" },
  { code: "KH", name: "Cambodia", flag: "🇰🇭" },
  { code: "LA", name: "Laos", flag: "🇱🇦" },
  { code: "NP", name: "Nepal", flag: "🇳🇵" },
  { code: "BT", name: "Bhutan", flag: "🇧🇹" },
  { code: "MV", name: "Maldives", flag: "🇲🇻" },
  { code: "AF", name: "Afghanistan", flag: "🇦🇫" },
  { code: "KZ", name: "Kazakhstan", flag: "🇰🇿" },
  { code: "UZ", name: "Uzbekistan", flag: "🇺🇿" },
  { code: "TJ", name: "Tajikistan", flag: "🇹🇯" },
  { code: "KG", name: "Kyrgyzstan", flag: "🇰🇬" },
  { code: "TM", name: "Turkmenistan", flag: "🇹🇲" },
  { code: "BY", name: "Belarus", flag: "🇧🇾" },
  { code: "MD", name: "Moldova", flag: "🇲🇩" },
  { code: "GE", name: "Georgia", flag: "🇬🇪" },
  { code: "AM", name: "Armenia", flag: "🇦🇲" },
  { code: "AZ", name: "Azerbaijan", flag: "🇦🇿" },
  { code: "LV", name: "Latvia", flag: "🇱🇻" },
  { code: "LT", name: "Lithuania", flag: "🇱🇹" },
  { code: "EE", name: "Estonia", flag: "🇪🇪" },
  { code: "HR", name: "Croatia", flag: "🇭🇷" },
  { code: "SI", name: "Slovenia", flag: "🇸🇮" },
  { code: "SK", name: "Slovakia", flag: "🇸🇰" },
  { code: "HU", name: "Hungary", flag: "🇭🇺" },
  { code: "RO", name: "Romania", flag: "🇷🇴" },
  { code: "BG", name: "Bulgaria", flag: "🇧🇬" },
  { code: "RS", name: "Serbia", flag: "🇷🇸" },
  { code: "ME", name: "Montenegro", flag: "🇲🇪" },
  { code: "BA", name: "Bosnia and Herzegovina", flag: "🇧🇦" },
  { code: "MK", name: "North Macedonia", flag: "🇲🇰" },
  { code: "AL", name: "Albania", flag: "🇦🇱" },
  { code: "XK", name: "Kosovo", flag: "🇽🇰" },
  { code: "MT", name: "Malta", flag: "🇲🇹" },
  { code: "CY", name: "Cyprus", flag: "🇨🇾" },
  { code: "LU", name: "Luxembourg", flag: "🇱🇺" },
  { code: "IS", name: "Iceland", flag: "🇮🇸" },
]

export function getCountryName(code: string): string {
  const country = COUNTRIES.find((c) => c.code === code)
  return country?.name || code
}

export function getCountryCode(name: string): string {
  const country = COUNTRIES.find((c) => c.name === name)
  return country?.code || ""
}

// Country coordinates for latitude and longitude
export const COUNTRY_COORDINATES: Record<string, { latitude: number; longitude: number }> = {
  US: { latitude: 37.0902, longitude: -95.7129 },
  GB: { latitude: 55.3781, longitude: -3.436 },
  CA: { latitude: 56.1304, longitude: -106.3468 },
  AU: { latitude: -25.2744, longitude: 133.7751 },
  DE: { latitude: 51.1657, longitude: 10.4515 },
  FR: { latitude: 46.2276, longitude: 2.2137 },
  IT: { latitude: 41.8719, longitude: 12.5674 },
  ES: { latitude: 40.463667, longitude: -3.74922 },
  NL: { latitude: 52.1326, longitude: 5.291266 },
  BE: { latitude: 50.5039, longitude: 4.4699 },
  CH: { latitude: 46.8182, longitude: 8.2275 },
  AT: { latitude: 47.5162, longitude: 14.5501 },
  SE: { latitude: 60.128161, longitude: 18.643501 },
  NO: { latitude: 60.472024, longitude: 8.468946 },
  DK: { latitude: 56.26392, longitude: 9.50195 },
  FI: { latitude: 61.924010, longitude: 25.748151 },
  PL: { latitude: 51.9194, longitude: 19.1451 },
  CZ: { latitude: 49.8175, longitude: 15.4730 },
  PT: { latitude: 39.3999, longitude: -8.2245 },
  GR: { latitude: 39.0742, longitude: 21.8243 },
  IE: { latitude: 53.4129, longitude: -8.2439 },
  JP: { latitude: 36.2048, longitude: 138.2529 },
  CN: { latitude: 35.8617, longitude: 104.1954 },
  IN: { latitude: 20.5937, longitude: 78.9629 },
  SG: { latitude: 1.3521, longitude: 103.8198 },
  MY: { latitude: 4.2105, longitude: 101.6964 },
  TH: { latitude: 15.870032, longitude: 100.992541 },
  PH: { latitude: 12.8797, longitude: 121.7740 },
  ID: { latitude: -0.7893, longitude: 113.9213 },
  VN: { latitude: 14.0583, longitude: 108.2772 },
  KR: { latitude: 35.9078, longitude: 127.7669 },
  NG: { latitude: 9.0820, longitude: 8.6753 },
  ZA: { latitude: -30.5595, longitude: 22.9375 },
  EG: { latitude: 26.8206, longitude: 30.8025 },
  KE: { latitude: -0.0236, longitude: 37.9062 },
  GH: { latitude: 7.3697, longitude: -5.3677 },
  BR: { latitude: -14.2350, longitude: -51.9253 },
  MX: { latitude: 23.6345, longitude: -102.5528 },
  AR: { latitude: -38.4161, longitude: -63.6167 },
  CL: { latitude: -35.6751, longitude: -71.5430 },
  CO: { latitude: 4.5709, longitude: -74.2973 },
  PE: { latitude: -9.1900, longitude: -75.0152 },
  ZW: { latitude: -19.0154, longitude: 29.1549 },
  RU: { latitude: 61.52401, longitude: 105.318756 },
  UA: { latitude: 48.3794, longitude: 31.1656 },
  TR: { latitude: 38.9637, longitude: 35.2433 },
  SA: { latitude: 23.8859, longitude: 45.0792 },
  AE: { latitude: 23.4241, longitude: 53.8478 },
  IL: { latitude: 31.0461, longitude: 34.8516 },
  PK: { latitude: 30.3753, longitude: 69.3451 },
  BD: { latitude: 23.6850, longitude: 90.3563 },
  LK: { latitude: 7.8731, longitude: 80.7718 },
  HK: { latitude: 22.3193, longitude: 114.1694 },
  TW: { latitude: 23.6978, longitude: 120.9605 },
  NZ: { latitude: -40.9006, longitude: 174.8860 },
}
